.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. clam_qt test_clam_qt
clean: FORCE
	$(MAKE) -C .. clam_qt_clean test_clam_qt_clean
check: FORCE
	$(MAKE) -C .. test_clam_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. clam_qt
