#include <clamspeech.h>

using namespace std;

vector<string> clamSpeechList;
vector<string> clamSpeech;
vector<string> clamourClamSpeech;
vector<string> quoteList;
CWeightedSpeech weightedStakeSpeech;

void CSLoad() {
    const char *texts[] = {
        "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks. -Satoshi Nakamoto",
        "If you don’t believe me or don’t get it, I don’t have time to try to convince you, sorry. -Satoshi Nakamoto",
        "Institutional momentum is to stick with the last decision. -Satoshi Nakamoto",
        "WikiLeaks has kicked the hornet’s nest, and the swarm is headed towards us. -Satoshi Nakamoto",
        "I am not Dorian Nakamoto. -Satoshi Nakamoto",
        "It is regulated by algorithm instead of being regulated by government bureaucracies. Un-corrupted. -Andreas Antonopolous",
        "...if a government bans bitcoin it will instantly be more credible as an alternative choice. -Andreas Antonopolous",
        "Bitcoin will survive the banking regulators and oppressive governments. The converse however is unlikely. -Andreas Antonopolous",
        "Countries rejecting bitcoin reminds me of the time when countries were resisting the Internet. -Andreas Antonopolous",
        "Most people are yet to understand how disruptive the Bitcoin technology really is. -Andreas Antonopolous",
        "Bitcoin’s success is owed to creativity and innovation. It has nothing to do with the government’s endorsement -Andreas Antonopolous",
        "Bitcoin is global, decentralized and unstoppable. Let government try, it will be hilarious to watch. -Andreas Antonopolous",
        "When the regulators come to regulate Bitcoin for your own good, your reply should be ‘Fuck Off! -Andreas Antonopolous",
        "Expression of Religious Freedom: The Great CLAM",
        "Expression of Religious Freedom: Atheism",
        "Expression of Religious Freedom: Agnosticism",
        "Expression of Religious Freedom: Bábism",
        "Expression of Religious Freedom: Bahá'í Faith",
        "Expression of Religious Freedom: Christianity",
        "Expression of Religious Freedom: Mormonism",
        "Expression of Religious Freedom: Gnosticism",
        "Expression of Religious Freedom: Islam",
        "Expression of Religious Freedom: Druze",
        "Expression of Religious Freedom: Judaism",
        "Expression of Religious Freedom: Black Hebrew Israelites",
        "Expression of Religious Freedom: Rastafari",
        "Expression of Religious Freedom: Mandaeism",
        "Expression of Religious Freedom: Sabianism",
        "Expression of Religious Freedom: Shabakism",
        "Expression of Religious Freedom: Ayyavazhi",
        "Expression of Religious Freedom: Bhakti",
        "Expression of Religious Freedom: Buddhism",
        "Expression of Religious Freedom: Din-e Ilahi",
        "Expression of Religious Freedom: Hinduism",
        "Expression of Religious Freedom: Jainism",
        "Expression of Religious Freedom: Meivazhi",
        "Expression of Religious Freedom: Sikhism",
        "Expression of Religious Freedom: Zoroastrianism",
        "Expression of Religious Freedom: Gnosticism",
        "Expression of Religious Freedom: Bábí",
        "Expression of Religious Freedom: Yazdânism",
        "Expression of Religious Freedom: Confucianism",
        "Expression of Religious Freedom: Shinto",
        "Expression of Religious Freedom: Taoism",
        "Expression of Religious Freedom: Chan Buddhism",
        "Expression of Religious Freedom: Chinese Folk",
        "Expression of Religious Freedom: Falun Gong",
        "Expression of Religious Freedom: Yiguandao",
        "Expression of Religious Freedom: Mohism",
        "Expression of Religious Freedom: Xiantiandao",
        "Expression of Religious Freedom: Cheondoism",
        "Expression of Religious Freedom: Daejongism",
        "Expression of Religious Freedom: Daesun Jinrihoe",
        "Expression of Religious Freedom: Gasin",
        "Expression of Religious Freedom: Jeung San Do",
        "Expression of Religious Freedom: Juche",
        "Expression of Religious Freedom: Korean Shamanism",
        "Expression of Religious Freedom: Suwunism",
        "Expression of Religious Freedom: Batuque",
        "Expression of Religious Freedom: Candomblé",
        "Expression of Religious Freedom: Dahomey Mythology",
        "Expression of Religious Freedom: Haitian Mythology",
        "Expression of Religious Freedom: Kumina",
        "Expression of Religious Freedom: Macumba",
        "Expression of Religious Freedom: Mami Wata",
        "Expression of Religious Freedom: Obeah",
        "Expression of Religious Freedom: Oyotunji",
        "Expression of Religious Freedom: Palo",
        "Expression of Religious Freedom: Quimbanda",
        "Expression of Religious Freedom: Santería",
        "Expression of Religious Freedom: Umbanda",
        "Expression of Religious Freedom: Vodou",
        "Expression of Religious Freedom: Akan Mythology",
        "Expression of Religious Freedom: Ashanti Mythology",
        "Expression of Religious Freedom: Dahomey Mythology",
        "Expression of Religious Freedom: Efik Mythology",
        "Expression of Religious Freedom: Igbo Mythology",
        "Expression of Religious Freedom: Isoko Mythology",
        "Expression of Religious Freedom: Yoruba Mythology",
        "Expression of Religious Freedom: Bushongo Mythology",
        "Expression of Religious Freedom: Bambuti Mythology",
        "Expression of Religious Freedom: Lugbara Mythology",
        "Expression of Religious Freedom: Akamba Mythology",
        "Expression of Religious Freedom: Dinka Mythology",
        "Expression of Religious Freedom: Lotuko Mythology",
        "Expression of Religious Freedom: Masai Mythology",
        "Expression of Religious Freedom: Khoisan",
        "Expression of Religious Freedom: Lozi Mythology",
        "Expression of Religious Freedom: Tumbuka Mythology",
        "Expression of Religious Freedom: Zulu Mythology",
        "Expression of Religious Freedom: Abenaki Mythology",
        "Expression of Religious Freedom: Anishinaabe",
        "Expression of Religious Freedom: Aztec Mythology",
        "Expression of Religious Freedom: Blackfoot Mythology",
        "Expression of Religious Freedom: Cherokee Mythology",
        "Expression of Religious Freedom: Chickasaw Mythology",
        "Expression of Religious Freedom: Choctaw Mythology",
        "Expression of Religious Freedom: Creek Mythology",
        "Expression of Religious Freedom: Crow Mythology",
        "Expression of Religious Freedom: Ghost Dance",
        "Expression of Religious Freedom: Guarani Mythology",
        "Expression of Religious Freedom: Haida Mythology",
        "Expression of Religious Freedom: Ho-Chunk Mythology",
        "Expression of Religious Freedom: Hopi Mythology",
        "Expression of Religious Freedom: Inca Mythology",
        "Expression of Religious Freedom: Indian Shaker",
        "Expression of Religious Freedom: Inuit Mythology",
        "Expression of Religious Freedom: Iroquois Mythology",
        "Expression of Religious Freedom: Keetoowah Nighthawk",
        "Expression of Religious Freedom: Kuksu",
        "Expression of Religious Freedom: Kwakiutl Mythology",
        "Expression of Religious Freedom: Lakota Mythology",
        "Expression of Religious Freedom: Leni Lenape Mythology",
        "Expression of Religious Freedom: Longhouse",
        "Expression of Religious Freedom: Mapuche Mythology",
        "Expression of Religious Freedom: Maya Mythology",
        "Expression of Religious Freedom: Midewiwin",
        "Expression of Religious Freedom: Miwok",
        "Expression of Religious Freedom: Native American",
        "Expression of Religious Freedom: Navajo Mythology",
        "Expression of Religious Freedom: Nootka Mythology",
        "Expression of Religious Freedom: Ohlone Mythology",
        "Expression of Religious Freedom: Olmec Mythology",
        "Expression of Religious Freedom: Pomo Mythology",
        "Expression of Religious Freedom: Pawnee Mythology",
        "Expression of Religious Freedom: Salish Mythology",
        "Expression of Religious Freedom: Selk'nam",
        "Expression of Religious Freedom: Seneca Mythology",
        "Expression of Religious Freedom: Southeastern Ceremonial",
        "Expression of Religious Freedom: Sun Dance",
        "Expression of Religious Freedom: Tsimshian Mythology",
        "Expression of Religious Freedom: Urarina",
        "Expression of Religious Freedom: Ute Mythology",
        "Expression of Religious Freedom: Wyandot",
        "Expression of Religious Freedom: Zuni Mythology",
        "Expression of Religious Freedom: Benzhuism",
        "Expression of Religious Freedom: Bimoism",
        "Expression of Religious Freedom: Bon",
        "Expression of Religious Freedom: Chinese Mythology",
        "Expression of Religious Freedom: Japanese Mythology",
        "Expression of Religious Freedom: Korean Shamanism",
        "Expression of Religious Freedom: Koshinto",
        "Expression of Religious Freedom: Manchu Shamanism",
        "Expression of Religious Freedom: Mun",
        "Expression of Religious Freedom: Siberian Shamanism",
        "Expression of Religious Freedom: Tengrism",
        "Expression of Religious Freedom: Ua Dab",
        "Expression of Religious Freedom: Vietnamese Folk",
        "Expression of Religious Freedom: Asatru",
        "Expression of Religious Freedom: Estonian Mythology",
        "Expression of Religious Freedom: Eskimo",
        "Expression of Religious Freedom: Finnish Mythology",
        "Expression of Religious Freedom: Finnish Paganism",
        "Expression of Religious Freedom: Marla",
        "Expression of Religious Freedom: Odinism",
        "Expression of Religious Freedom: Romuva",
        "Expression of Religious Freedom: Hungarian Folk",
        "Expression of Religious Freedom: Sami",
        "Expression of Religious Freedom: Wotanism",
        "Expression of Religious Freedom: Australian Aboriginal Mythology",
        "Expression of Religious Freedom: Balinese Mythology",
        "Expression of Religious Freedom: Javanese",
        "Expression of Religious Freedom: Melanesian Mythology",
        "Expression of Religious Freedom: Micronesian Mythology",
        "Expression of Religious Freedom: Modekngei",
        "Expression of Religious Freedom: Nauruan",
        "Expression of Religious Freedom: Philippine Mythology",
        "Expression of Religious Freedom: Anito",
        "Expression of Religious Freedom: Gabâ",
        "Expression of Religious Freedom: Kulam",
        "Expression of Religious Freedom: Polynesian Mythology",
        "Expression of Religious Freedom: Hawaiian Mythology",
        "Expression of Religious Freedom: Maori Mythology",
        "Expression of Religious Freedom: Rapa Nui Mythology",
        "Expression of Religious Freedom: Moai",
        "Expression of Religious Freedom: Tangata Manu",
        "Expression of Religious Freedom: John Frum",
        "Expression of Religious Freedom: Johnson Cult",
        "Expression of Religious Freedom: Prince Philip Movement",
        "Expression of Religious Freedom: Vailala Madness",
        "Expression of Religious Freedom: Ancient Egyptian",
        "Expression of Religious Freedom: Ancient Semitic",
        "Expression of Religious Freedom: Canaanite Mythology",
        "Expression of Religious Freedom: Mesopotamian Mythology",
        "Expression of Religious Freedom: Arabian Mythology",
        "Expression of Religious Freedom: Assyrian Mythology",
        "Expression of Religious Freedom: Babylonian Mythology",
        "Expression of Religious Freedom: Chaldean Mythology",
        "Expression of Religious Freedom: Sumerian Mythology",
        "Expression of Religious Freedom: Proto-Indo-Iranian",
        "Expression of Religious Freedom: Historical Vedic",
        "Expression of Religious Freedom: Iranian Mythology",
        "Expression of Religious Freedom: Armenian Mythology",
        "Expression of Religious Freedom: Baltic Polytheism",
        "Expression of Religious Freedom: Celtic Polytheism",
        "Expression of Religious Freedom: Brythonic Mythology",
        "Expression of Religious Freedom: Gaelic Mythology",
        "Expression of Religious Freedom: Germanic Polytheism",
        "Expression of Religious Freedom: Anglo-Saxon",
        "Expression of Religious Freedom: Continental Germanic",
        "Expression of Religious Freedom: Norse",
        "Expression of Religious Freedom: Greek Polytheism",
        "Expression of Religious Freedom: Hittite Mythology",
        "Expression of Religious Freedom: Persian Mythology",
        "Expression of Religious Freedom: Roman Polytheism",
        "Expression of Religious Freedom: Slavic Polytheism",
        "Expression of Religious Freedom: Eleusinian Mysteries",
        "Expression of Religious Freedom: Mithraism",
        "Expression of Religious Freedom: Orphism",
        "Expression of Religious Freedom: Pythagoreanism",
        "Expression of Religious Freedom: Gallo-Roman",
        "Expression of Religious Freedom: Estonian Polytheism",
        "Expression of Religious Freedom: Finnish Polytheism",
        "Expression of Religious Freedom: Hungarian Polytheism",
        "Expression of Religious Freedom: Hindu Mysticism",
        "Expression of Religious Freedom: Tantra",
        "Expression of Religious Freedom: Vaastu Shastra",
        "Expression of Religious Freedom: Moorish Science",
        "Expression of Religious Freedom: Moorish Orthodox",
        "Expression of Religious Freedom: Neoplatonism",
        "Expression of Religious Freedom: Pythagoreanism",
        "Expression of Religious Freedom: Neopythagoreanism",
        "Expression of Religious Freedom: Theosophy",
        "Expression of Religious Freedom: Sufism",
        "Expression of Religious Freedom: Hermeticism",
        "Expression of Religious Freedom: Builders of the Adytum",
        "Expression of Religious Freedom: Fraternitas Saturni",
        "Expression of Religious Freedom: Fraternity of the Inner Light",
        "Expression of Religious Freedom: Hermetic Order of the Golden Dawn",
        "Expression of Religious Freedom: The Open Source Order of the Golden Dawn",
        "Expression of Religious Freedom: Ordo Aurum Solis",
        "Expression of Religious Freedom: Rosicrucian",
        "Expression of Religious Freedom: Servants of the Light",
        "Expression of Religious Freedom: Ordo Templi Orientis",
        "Expression of Religious Freedom: Ecclesia Gnostica Catholica",
        "Expression of Religious Freedom: Typhonian Order",
        "Expression of Religious Freedom: Anthroposophy",
        "Expression of Religious Freedom: Behmenism",
        "Expression of Religious Freedom: Christian Kabbalah",
        "Expression of Religious Freedom: Martinism",
        "Expression of Religious Freedom: Ceremonial Magic",
        "Expression of Religious Freedom: Enochian Magic",
        "Expression of Religious Freedom: Goetic Magic",
        "Expression of Religious Freedom: Chaos Magic",
        "Expression of Religious Freedom: Illuminates of Thanateros",
        "Expression of Religious Freedom: Thee Temple ov Psychick Youth",
        "Expression of Religious Freedom: Hoodoo",
        "Expression of Religious Freedom: New Orleans Voodoo",
        "Expression of Religious Freedom: Kulam",
        "Expression of Religious Freedom: Pow-Wow",
        "Expression of Religious Freedom: Seiðr",
        "Expression of Religious Freedom: Magick",
        "Expression of Religious Freedom: Witchcraft",
        "Expression of Religious Freedom: Adonism",
        "Expression of Religious Freedom: Church of All Worlds",
        "Expression of Religious Freedom: Church of Aphrodite",
        "Expression of Religious Freedom: Feraferia",
        "Expression of Religious Freedom: Neo-Druidism",
        "Expression of Religious Freedom: Reformed Druids",
        "Expression of Religious Freedom: Neoshamanism",
        "Expression of Religious Freedom: Neo-völkisch",
        "Expression of Religious Freedom: Technopaganism",
        "Expression of Religious Freedom: Wicca",
        "Expression of Religious Freedom: British Traditional Wicca",
        "Expression of Religious Freedom: Gardnerian Wicca",
        "Expression of Religious Freedom: Alexandrian Wicca",
        "Expression of Religious Freedom: Central Valley Wicca",
        "Expression of Religious Freedom: Algard Wicca",
        "Expression of Religious Freedom: Chthonioi Alexandrian Wicca",
        "Expression of Religious Freedom: Blue Star Wicca",
        "Expression of Religious Freedom: Eclectic Wicca",
        "Expression of Religious Freedom: Celtic Wicca",
        "Expression of Religious Freedom: Saxon Wicca",
        "Expression of Religious Freedom: Dianic Wicca",
        "Expression of Religious Freedom: McFarland Dianic Wicca",
        "Expression of Religious Freedom: Faery Wicca",
        "Expression of Religious Freedom: Correllian Nativist",
        "Expression of Religious Freedom: Georgian Wicca",
        "Expression of Religious Freedom: Odyssean Wicca",
        "Expression of Religious Freedom: Covenant of the Goddess",
        "Expression of Religious Freedom: Baltic Neopaganism",
        "Expression of Religious Freedom: Celtic Neopaganism",
        "Expression of Religious Freedom: Finnish Neopaganism",
        "Expression of Religious Freedom: Germanic Neopaganism",
        "Expression of Religious Freedom: Hellenismos",
        "Expression of Religious Freedom: Kemetism",
        "Expression of Religious Freedom: Roman Neopaganism",
        "Expression of Religious Freedom: Semitic Neopaganism",
        "Expression of Religious Freedom: Slavic Neopaganism",
        "Expression of Religious Freedom: Taaraism",
        "Expression of Religious Freedom: Zalmoxianism",
        "Expression of Religious Freedom: Creativity",
        "Expression of Religious Freedom: Huna",
        "Expression of Religious Freedom: Raëlism",
        "Expression of Religious Freedom: Scientology",
        "Expression of Religious Freedom: Unitarian Universalist",
        "Expression of Religious Freedom: Christian Science",
        "Expression of Religious Freedom: Church Universal and Triumphant",
        "Expression of Religious Freedom: Divine Science",
        "Expression of Religious Freedom: Religious Science",
        "Expression of Religious Freedom: Unity Church",
        "Expression of Religious Freedom: Jewish Science",
        "Expression of Religious Freedom: Seicho-no-Ie",
        "Expression of Religious Freedom: Church of World Messianity",
        "Expression of Religious Freedom: Happy Science",
        "Expression of Religious Freedom: Konkokyo",
        "Expression of Religious Freedom: Oomoto",
        "Expression of Religious Freedom: PL Kyodan",
        "Expression of Religious Freedom: Seicho-No-Ie",
        "Expression of Religious Freedom: Tenrikyo",
        "Expression of Religious Freedom: Satanism",
        "Expression of Religious Freedom: LaVeyan Satanism",
        "Expression of Religious Freedom: Theistic Satanism",
        "Expression of Religious Freedom: Our Lady of Endor Coven",
        "Expression of Religious Freedom: Demonolatry",
        "Expression of Religious Freedom: Luciferianism",
        "Expression of Religious Freedom: Setianism",
        "Expression of Religious Freedom: Discordianism",
        "Expression of Religious Freedom: Ethical Culture",
        "Expression of Religious Freedom: Freethought",
        "Expression of Religious Freedom: Jesusism",
        "Expression of Religious Freedom: Naturalistic Pantheism",
        "Expression of Religious Freedom: Secular Humanism",
        "Expression of Religious Freedom: Yoism",
        "Expression of Religious Freedom: Church of Euthanasia",
        "Expression of Religious Freedom: Pastafarianism",
        "Expression of Religious Freedom: Church of the SubGenius",
        "Expression of Religious Freedom: Dudeism",
        "Expression of Religious Freedom: Iglesia Maradoniana",
        "Expression of Religious Freedom: Invisible Pink Unicorn",
        "Expression of Religious Freedom: Jediism",
        "Expression of Religious Freedom: Kibology",
        "Expression of Religious Freedom: Landover Baptist",
        "Expression of Religious Freedom: Last Thursdayism",
        "Expression of Religious Freedom: Cult of the Supreme Being",
        "Expression of Religious Freedom: Deism",
        "Expression of Religious Freedom: Eckankar",
        "Expression of Religious Freedom: Fourth Way",
        "Expression of Religious Freedom: Goddess Movement",
        "Expression of Religious Freedom: Humanism",
        "Expression of Religious Freedom: The New Message from God",
        "Expression of Religious Freedom: Nuwaubian Nation",
        "Expression of Religious Freedom: Open-source",
        "Expression of Religious Freedom: Plurationalism",
        "Expression of Religious Freedom: Spiritism",
        "Expression of Religious Freedom: Subud",
        "Expression of Religious Freedom: Universal Life",
        "Expression of Political Freedom: Libertarianism",
        "Expression of Political Freedom: Far-left",
        "Expression of Political Freedom: Left-wing",
        "Expression of Political Freedom: Center-left",
        "Expression of Political Freedom: Center",
        "Expression of Political Freedom: Center-right",
        "Expression of Political Freedom: Right-wing",
        "Expression of Political Freedom: Far-right",
        "Expression of Political Freedom: Radical left",
        "Expression of Political Freedom: Radical center",
        "Expression of Political Freedom: Radical right",
        "Expression of Political Freedom: Radicalism",
        "Expression of Political Freedom: Liberalism",
        "Expression of Political Freedom: Moderate",
        "Expression of Political Freedom: Conservatism",
        "Expression of Political Freedom: Reactionism",
        "Expression of Political Freedom: Libertarianism",
        "Expression of Political Freedom: Syncretic",
        "Expression of Political Freedom: Extremism",
        "Expression of Political Freedom: Partisan",
        "Expression of Political Freedom: Fundamentalism",
        "Expression of Political Freedom: Fanaticism",
        "Expression of Political Freedom: Dominant-party",
        "Expression of Political Freedom: Non-partisan",
        "Expression of Political Freedom: Single-party",
        "Expression of Political Freedom: Two-party",
        "Expression of Political Freedom: Multi-party",
        "Expression of Political Freedom: Minority Government",
        "Expression of Political Freedom: Confidence & Supply",
        "Expression of Political Freedom: Rainbow Coalition",
        "Expression of Political Freedom: Full Coalition",
        "Expression of Political Freedom: Majority Government",
        "Expression of Political Freedom: Grand Coalition",
        "Expression of Political Freedom: National Unity Government",
        "Expression of Political Freedom: Confederation",
        "Expression of Political Freedom: Federation",
        "Expression of Political Freedom: Hegemony",
        "Expression of Political Freedom: Empire",
        "Expression of Political Freedom: Unitary state",
        "Expression of Political Freedom: Autocracy",
        "Expression of Political Freedom: Despotism",
        "Expression of Political Freedom: Dictatorship",
        "Expression of Political Freedom: Totalitarianism",
        "Expression of Political Freedom: Direct Democracy",
        "Expression of Political Freedom: Representative Democracy",
        "Expression of Political Freedom: Absolute Monarchy",
        "Expression of Political Freedom: Constitutional Monarchy",
        "Expression of Political Freedom: Aristocracy",
        "Expression of Political Freedom: Military junta",
        "Expression of Political Freedom: Plutocracy",
        "Expression of Political Freedom: Stratocracy",
        "Expression of Political Freedom: Timocracy",
        "Expression of Political Freedom: Anarchy",
        "Expression of Political Freedom: Anocracy",
        "Expression of Political Freedom: Kritarchy",
        "Expression of Political Freedom: Particracy",
        "Expression of Political Freedom: Republic",
        "Expression of Political Freedom: Theocracy",
        "Expression of Political Freedom: Anarchism",
        "Expression of Political Freedom: Anarchism without adjectives",
        "Expression of Political Freedom: Individualist anarchism",
        "Expression of Political Freedom: Religious anarchism",
        "Expression of Political Freedom: Social anarchism",
        "Expression of Political Freedom: Anarchist communism",
        "Expression of Political Freedom: Communism",
        "Expression of Political Freedom: Marxism",
        "Expression of Political Freedom: Revisionism",
        "Expression of Political Freedom: Leninism",
        "Expression of Political Freedom: Anti-revisionism",
        "Expression of Political Freedom: Conservatism",
        "Expression of Political Freedom: Environmentalism",
        "Expression of Political Freedom: Gender equality",
        "Expression of Political Freedom: Feminism",
        "Expression of Political Freedom: Religious feminism",
        "Expression of Political Freedom: LGBT",
        "Expression of Political Freedom: Masculism",
        "Expression of Political Freedom: Libertarianism",
        "Expression of Political Freedom: Libertarian socialism",
        "Expression of Political Freedom: Right libertarianism",
        "Expression of Political Freedom: Fascism",
        "Expression of Political Freedom: Zionism",
        "Expression of Political Freedom: Unification movements",
        "Expression of Political Freedom: Buddhism",
        "Expression of Political Freedom: Christianity",
        "Expression of Political Freedom: Hinduism",
        "Expression of Political Freedom: Islam",
        "Expression of Political Freedom: Judaism",
        "Expression of Political Freedom: Mormonism",
        "Expression of Political Freedom: Sikhism",
        "Expression of Political Freedom: Socialism",
        "Expression of Political Freedom: Libertarian Marxism",
        "Expression of Political Freedom: Reformist socialism",
        "Expression of Political Freedom: Democratic socialism",
        "Expression of Political Freedom: Social democracy",
        "Expression of Political Freedom: Religious socialism",
        "Expression of Political Freedom: Revolutionary socialism",
        "Expression of Political Freedom: Synthesis anarchism",
        "Expression of Political Freedom: Anarchist naturism",
        "Expression of Political Freedom: Egoist anarchism",
        "Expression of Political Freedom: Freiwirtschaft",
        "Expression of Political Freedom: Geoanarchism",
        "Expression of Political Freedom: Inclusive Democracy",
        "Expression of Political Freedom: Individualist anarchism",
        "Expression of Political Freedom: Insurrectionary anarchism",
        "Expression of Political Freedom: Illegalism",
        "Expression of Political Freedom: Mutualism",
        "Expression of Political Freedom: Buddhist anarchism",
        "Expression of Political Freedom: Christian anarchism",
        "Expression of Political Freedom: Islamic anarchism",
        "Expression of Political Freedom: Jewish anarchism",
        "Expression of Political Freedom: Anarcha-feminism",
        "Expression of Political Freedom: Anarcho-syndicalism",
        "Expression of Political Freedom: Collectivist anarchism",
        "Expression of Political Freedom: Participatory economics",
        "Expression of Political Freedom: Social anarchism",
        "Expression of Political Freedom: Social ecology",
        "Expression of Political Freedom: Magonism",
        "Expression of Political Freedom: Platformism",
        "Expression of Political Freedom: Autarchism",
        "Expression of Political Freedom: Autonomism",
        "Expression of Political Freedom: Crypto-anarchism",
        "Expression of Political Freedom: Indigenism",
        "Expression of Political Freedom: Infoanarchism",
        "Expression of Political Freedom: Makhnovism",
        "Expression of Political Freedom: National-Anarchism",
        "Expression of Political Freedom: Panarchism",
        "Expression of Political Freedom: Platformism",
        "Expression of Political Freedom: Post-anarchism",
        "Expression of Political Freedom: Post-left anarchy",
        "Expression of Political Freedom: Queer anarchism",
        "Expression of Political Freedom: Workerism",
        "Expression of Political Freedom: Pluralism",
        "Expression of Political Freedom: Stateless communism",
        "Expression of Political Freedom: Revolutionary socialism",
        "Expression of Political Freedom: Neo-Marxism",
        "Expression of Political Freedom: Classical Marxism",
        "Expression of Political Freedom: Autonomism",
        "Expression of Political Freedom: Luxemburgism",
        "Expression of Political Freedom: Left communism",
        "Expression of Political Freedom: Communization",
        "Expression of Political Freedom: Council communism",
        "Expression of Political Freedom: Titoism",
        "Expression of Political Freedom: Castroism",
        "Expression of Political Freedom: Religious communism",
        "Expression of Political Freedom: Christian communism",
        "Expression of Political Freedom: Anarchist communism",
        "Expression of Political Freedom: Platformism",
        "Expression of Political Freedom: Eurocommunism",
        "Expression of Political Freedom: Orthodox Marxism",
        "Expression of Political Freedom: Leninism",
        "Expression of Political Freedom: Marxism–Leninism",
        "Expression of Political Freedom: Guevarism",
        "Expression of Political Freedom: World communism",
        "Expression of Political Freedom: Primitive communism",
        "Expression of Political Freedom: Scientific communism",
        "Expression of Political Freedom: Stalinism",
        "Expression of Political Freedom: Maoism",
        "Expression of Political Freedom: Ho Chi Minh Thought",
        "Expression of Political Freedom: Hoxhaism",
        "Expression of Political Freedom: Conservative liberalism",
        "Expression of Political Freedom: Cultural conservatism",
        "Expression of Political Freedom: Liberal conservatism",
        "Expression of Political Freedom: Libertarian conservatism",
        "Expression of Political Freedom: National conservatism",
        "Expression of Political Freedom: Neoconservatism",
        "Expression of Political Freedom: Paleoconservatism",
        "Expression of Political Freedom: Social conservatism",
        "Expression of Political Freedom: Agrarianism",
        "Expression of Political Freedom: Bioconservatism",
        "Expression of Political Freedom: Black conservatism",
        "Expression of Political Freedom: Carlism",
        "Expression of Political Freedom: Civic Conservatism",
        "Expression of Political Freedom: Christian democracy",
        "Expression of Political Freedom: Communitarianism",
        "Expression of Political Freedom: Fiscal conservatism",
        "Expression of Political Freedom: Green conservatism",
        "Expression of Political Freedom: Latin Conservatism",
        "Expression of Political Freedom: Monarchism",
        "Expression of Political Freedom: Right-libertarianism",
        "Expression of Political Freedom: Roman Catholic conservatism",
        "Expression of Political Freedom: Theoconservatism",
        "Expression of Political Freedom: Toryism",
        "Expression of Political Freedom: Traditionalist conservatism",
        "Expression of Political Freedom: Reactionary",
        "Expression of Political Freedom: Anarchist naturism",
        "Expression of Political Freedom: Anarcho-primitivism",
        "Expression of Political Freedom: Bioregionalism",
        "Expression of Political Freedom: Bright green environmentalism",
        "Expression of Political Freedom: Deep ecology",
        "Expression of Political Freedom: Eco-capitalism",
        "Expression of Political Freedom: Ecofascism",
        "Expression of Political Freedom: Ecofeminism",
        "Expression of Political Freedom: Eco-socialism",
        "Expression of Political Freedom: Environmentalism",
        "Expression of Political Freedom: Free-market environmentalism",
        "Expression of Political Freedom: Green anarchism",
        "Expression of Political Freedom: Green conservatism",
        "Expression of Political Freedom: Green liberalism",
        "Expression of Political Freedom: Green libertarianism",
        "Expression of Political Freedom: Green politics",
        "Expression of Political Freedom: Green municipalism",
        "Expression of Political Freedom: Green syndicalism",
        "Expression of Political Freedom: Social ecology",
        "Expression of Political Freedom: Cultural feminism",
        "Expression of Political Freedom: Ecofeminism",
        "Expression of Political Freedom: Feminism",
        "Expression of Political Freedom: Individualist feminism",
        "Expression of Political Freedom: Lesbian feminism",
        "Expression of Political Freedom: Liberal feminism",
        "Expression of Political Freedom: Marxist feminism",
        "Expression of Political Freedom: Masculism",
        "Expression of Political Freedom: Postmodern feminism",
        "Expression of Political Freedom: Psychoanalytic feminism",
        "Expression of Political Freedom: Radical feminism",
        "Expression of Political Freedom: Separatist feminism",
        "Expression of Political Freedom: Socialist feminism",
        "Expression of Political Freedom: Womanism",
        "Expression of Political Freedom: Religious feminism",
        "Expression of Political Freedom: Christian feminism",
        "Expression of Political Freedom: Islamic feminism",
        "Expression of Political Freedom: Jewish feminism",
        "Expression of Political Freedom: LGBT social movements",
        "Expression of Political Freedom: Classical liberalism",
        "Expression of Political Freedom: Conservative liberalism",
        "Expression of Political Freedom: Economic liberalism",
        "Expression of Political Freedom: Individualism",
        "Expression of Political Freedom: Liberal feminism",
        "Expression of Political Freedom: Liberal socialism",
        "Expression of Political Freedom: Liberalism",
        "Expression of Political Freedom: Market liberalism",
        "Expression of Political Freedom: National liberalism",
        "Expression of Political Freedom: Neoliberalism",
        "Expression of Political Freedom: Ordoliberalism",
        "Expression of Political Freedom: Paleoliberalism",
        "Expression of Political Freedom: Social liberalism",
        "Expression of Political Freedom: Colonial liberalism",
        "Expression of Political Freedom: Fourierism",
        "Expression of Political Freedom: Collectivist anarchism",
        "Expression of Political Freedom: Anarcho-communism",
        "Expression of Political Freedom: Anarcho-syndicalism",
        "Expression of Political Freedom: Guild socialism",
        "Expression of Political Freedom: Revolutionary syndicalism",
        "Expression of Political Freedom: Libertarian Marxism",
        "Expression of Political Freedom: Libertarian socialism",
        "Expression of Political Freedom: Left communism",
        "Expression of Political Freedom: Council communism",
        "Expression of Political Freedom: Platformism",
        "Expression of Political Freedom: Gandhian economics",
        "Expression of Political Freedom: Situationist International",
        "Expression of Political Freedom: Autonomism",
        "Expression of Political Freedom: Social ecology",
        "Expression of Political Freedom: Participism",
        "Expression of Political Freedom: Inclusive Democracy",
        "Expression of Political Freedom: Zapatismo",
        "Expression of Political Freedom: Insurrectionary anarchism",
        "Expression of Political Freedom: Communalism",
        "Expression of Political Freedom: Communization",
        "Expression of Political Freedom: Anarcho-capitalism",
        "Expression of Political Freedom: Classical liberalism",
        "Expression of Political Freedom: Libertarian conservatism",
        "Expression of Political Freedom: Minarchism",
        "Expression of Political Freedom: Objectivism",
        "Expression of Political Freedom: Paleolibertarianism",
        "Expression of Political Freedom: Right libertarianism",
        "Expression of Political Freedom: Voluntaryism",
        "Expression of Political Freedom: Agorism",
        "Expression of Political Freedom: Cultural liberalism",
        "Expression of Political Freedom: Geolibertarianism",
        "Expression of Political Freedom: Green liberalism",
        "Expression of Political Freedom: Individualist feminism",
        "Expression of Political Freedom: Progressivism",
        "Expression of Political Freedom: Radicalism",
        "Expression of Political Freedom: Internationalism",
        "Expression of Political Freedom: Liberal nationalism",
        "Expression of Political Freedom: Nationalism",
        "Expression of Political Freedom: Romantic nationalism",
        "Expression of Political Freedom: Austrofascism",
        "Expression of Political Freedom: Chilean Fascism",
        "Expression of Political Freedom: Clerical fascism",
        "Expression of Political Freedom: Ecofascism",
        "Expression of Political Freedom: Falangism",
        "Expression of Political Freedom: Greek fascism",
        "Expression of Political Freedom: Italian fascism",
        "Expression of Political Freedom: Iron Guard",
        "Expression of Political Freedom: Japanese fascism",
        "Expression of Political Freedom: Nazism",
        "Expression of Political Freedom: Neo-Fascism",
        "Expression of Political Freedom: Rexism",
        "Expression of Political Freedom: Strasserism",
        "Expression of Political Freedom: Ustaše",
        "Expression of Political Freedom: Zbor",
        "Expression of Political Freedom: Kemalism",
        "Expression of Political Freedom: Brazilian Integralism",
        "Expression of Political Freedom: Gaullism",
        "Expression of Political Freedom: Irish Nationalism",
        "Expression of Political Freedom: Irish Republicanism",
        "Expression of Political Freedom: Peronism",
        "Expression of Political Freedom: Portuguese Integralism",
        "Expression of Political Freedom: Baathism",
        "Expression of Political Freedom: Nasserism",
        "Expression of Political Freedom: Zionism",
        "Expression of Political Freedom: Labor Zionism",
        "Expression of Political Freedom: Religious Zionism",
        "Expression of Political Freedom: Revisionist Zionism",
        "Expression of Political Freedom: Neo-Zionism",
        "Expression of Political Freedom: African socialism",
        "Expression of Political Freedom: Arab socialism",
        "Expression of Political Freedom: Pan-Africanism",
        "Expression of Political Freedom: Pan-Arabism",
        "Expression of Political Freedom: Pan-Iranism",
        "Expression of Political Freedom: Pan-European nationalism",
        "Expression of Political Freedom: Arab nationalism",
        "Expression of Political Freedom: Black nationalism",
        "Expression of Political Freedom: Chinese nationalism",
        "Expression of Political Freedom: Corporatism",
        "Expression of Political Freedom: Left-wing nationalism",
        "Expression of Political Freedom: National-Anarchism",
        "Expression of Political Freedom: National Bolshevism",
        "Expression of Political Freedom: National syndicalism",
        "Expression of Political Freedom: Patriotism",
        "Expression of Political Freedom: Producerism",
        "Expression of Political Freedom: Queer nationalism",
        "Expression of Political Freedom: White nationalism",
        "Expression of Political Freedom: Theocracy",
        "Expression of Political Freedom: Buddhist socialism",
        "Expression of Political Freedom: Christian anarchism",
        "Expression of Political Freedom: Christian communism",
        "Expression of Political Freedom: Christian democracy",
        "Expression of Political Freedom: Christian feminism",
        "Expression of Political Freedom: Christian socialism",
        "Expression of Political Freedom: Christian Left",
        "Expression of Political Freedom: Clerical fascism",
        "Expression of Political Freedom: Liberation Theology",
        "Expression of Political Freedom: Political Catholicism",
        "Expression of Political Freedom: Popolarismo",
        "Expression of Political Freedom: Christian Right",
        "Expression of Political Freedom: Christian Zionism",
        "Expression of Political Freedom: Christofascism",
        "Expression of Political Freedom: Dominionism",
        "Expression of Political Freedom: Caesaropapism",
        "Expression of Political Freedom: Ultramontanism",
        "Expression of Political Freedom: Hindu nationalism",
        "Expression of Political Freedom: Islamic democracy",
        "Expression of Political Freedom: Islamic socialism",
        "Expression of Political Freedom: Islamism",
        "Expression of Political Freedom: Khilafat",
        "Expression of Political Freedom: Panislamism",
        "Expression of Political Freedom: Jewish anarchism",
        "Expression of Political Freedom: Jewish feminism",
        "Expression of Political Freedom: Religious Zionism",
        "Expression of Political Freedom: Theodemocracy",
        "Expression of Political Freedom: United Order",
        "Expression of Political Freedom: Khalistan movement",
        "Expression of Political Freedom: Fourierism",
        "Expression of Political Freedom: Guild socialism",
        "Expression of Political Freedom: Revolutionary syndicalism",
        "Expression of Political Freedom: Gandhian economics",
        "Expression of Political Freedom: Zapatismo",
        "Expression of Political Freedom: Autonomism",
        "Expression of Political Freedom: Situationist International",
        "Expression of Political Freedom: Libertarian Marxism",
        "Expression of Political Freedom: Luxemburgism",
        "Expression of Political Freedom: Left communism",
        "Expression of Political Freedom: Council communism",
        "Expression of Political Freedom: Communization",
        "Expression of Political Freedom: Collectivist anarchism",
        "Expression of Political Freedom: Anarcho-communism",
        "Expression of Political Freedom: Anarcho-syndicalism",
        "Expression of Political Freedom: Social anarchism",
        "Expression of Political Freedom: Platformism",
        "Expression of Political Freedom: Social ecology",
        "Expression of Political Freedom: Participism",
        "Expression of Political Freedom: Inclusive Democracy",
        "Expression of Political Freedom: Communalism",
        "Expression of Political Freedom: Bernsteinism",
        "Expression of Political Freedom: Austromarxism",
        "Expression of Political Freedom: Bernsteinism",
        "Expression of Political Freedom: Democratic socialism",
        "Expression of Political Freedom: Fabianism",
        "Expression of Political Freedom: Reformism",
        "Expression of Political Freedom: Market socialism",
        "Expression of Political Freedom: Neosocialism",
        "Expression of Political Freedom: Social democracy",
        "Expression of Political Freedom: State socialism",
        "Expression of Political Freedom: African socialism",
        "Expression of Political Freedom: Arab socialism",
        "Expression of Political Freedom: Bolivarianism",
        "Expression of Political Freedom: Labor Zionism",
        "Expression of Political Freedom: Melanesian socialism",
        "Expression of Political Freedom: Revolutionary democracy",
        "Expression of Political Freedom: Religious socialism",
        "Expression of Political Freedom: Liberation Theology",
        "Expression of Political Freedom: Social capitalism",
        "Expression of Political Freedom: Socialist feminism",
        "Expression of Political Freedom: Quotaism",
        "Expression of Political Freedom: Autonomist Marxism",
        "Expression of Political Freedom: Castroism",
        "Expression of Political Freedom: Council communism",
        "Expression of Political Freedom: De Leonism",
        "Expression of Political Freedom: Eurocommunism",
        "Expression of Political Freedom: Guevarism",
        "Expression of Political Freedom: Hoxhaism",
        "Expression of Political Freedom: Kautskyism",
        "Expression of Political Freedom: Left communism",
        "Expression of Political Freedom: Leninism",
        "Expression of Political Freedom: Luxemburgism",
        "Expression of Political Freedom: Maoism",
        "Expression of Political Freedom: Marxism",
        "Expression of Political Freedom: Marxism–Leninism",
        "Expression of Political Freedom: Marxist feminism",
        "Expression of Political Freedom: Marxist humanism",
        "Expression of Political Freedom: Neo-marxism",
        "Expression of Political Freedom: Orthodox Marxism",
        "Expression of Political Freedom: Situationism",
        "Expression of Political Freedom: Anti-Revisionism",
        "Expression of Political Freedom: Titoism",
        "Expression of Political Freedom: Trotskyism",
        "Expression of Political Freedom: Western Marxism",
        "Expression of Political Freedom: Anarcho-syndicalism",
        "Expression of Political Freedom: Collectivist anarchism",
        "Expression of Political Freedom: Anarchist communism",
        "Expression of Political Freedom: Eco-socialism",
        "Expression of Political Freedom: Social anarchism",
        "Expression of Political Freedom: Social ecology",
        "Expression of Political Freedom: Individualist anarchism",
        "Expression of Political Freedom: Mutualist anarchism",
        "Expression of Political Freedom: Guild socialism",
        "Expression of Political Freedom: Libertarian socialism",
        "Expression of Political Freedom: Sankarism",
        "Expression of Political Freedom: Syndicalism",
        "Expression of Political Freedom: Utopian socialism",
        "Expression of Political Freedom: National Bolshevism",
        "Expression of Political Freedom: Realism",
        "Expression of Political Freedom: Authoritarianism",
        "Expression of Political Freedom: Anarchism",
        "Expression of Political Freedom: Centrism",
        "Expression of Political Freedom: Christian democracy",
        "Expression of Political Freedom: Communism",
        "Expression of Political Freedom: Communitarianism",
        "Expression of Political Freedom: Conservatism",
        "Expression of Political Freedom: Fascism",
        "Expression of Political Freedom: Feminism",
        "Expression of Political Freedom: Green politics",
        "Expression of Political Freedom: Hegemonic masculinity",
        "Expression of Political Freedom: Individualism",
        "Expression of Political Freedom: Islamism",
        "Expression of Political Freedom: Left-wing politics",
        "Expression of Political Freedom: Liberalism",
        "Expression of Political Freedom: Libertarianism",
        "Expression of Political Freedom: Monarchism",
        "Expression of Political Freedom: Nationalism",
        "Expression of Political Freedom: Republicanism",
        "Expression of Political Freedom: Right-wing politics",
        "Expression of Political Freedom: Social democracy",
        "Expression of Political Freedom: Socialism",
        "Expression of Political Freedom: Utilitarianism"
    };

    unsigned int size = sizeof(texts) / sizeof(texts[0]);

    for (unsigned int i = 0; i < size; i++)
        clamSpeechList.push_back(texts[i]);
}
